/* ===========================================================================
 * PS/2 Keyboard Driver
 * ===========================================================================
 */

#ifndef PS2_HEADER
#define PS2_HEADER

#include <library.h>

bool ps2_enabled;
bool ps2_dual_channel;
bool ps2_port1;
bool ps2_port2;

void ps2_init();
u1 ps2_receive();

#define PS2_SCAN_CODE_A_PRESSED 0x1e
#define PS2_SCAN_CODE_A_RELEASED 0x9e
#define PS2_SCAN_CODE_B_PRESSED 0x30
#define PS2_SCAN_CODE_B_RELEASED 0xb0
#define PS2_SCAN_CODE_C_PRESSED 0x2e
#define PS2_SCAN_CODE_C_RELEASED 0xae
#define PS2_SCAN_CODE_D_PRESSED 0x20
#define PS2_SCAN_CODE_D_RELEASED 0xa0
#define PS2_SCAN_CODE_E_PRESSED 0x12
#define PS2_SCAN_CODE_E_RELEASED 0x92
#define PS2_SCAN_CODE_F_PRESSED 0x21
#define PS2_SCAN_CODE_F_RELEASED 0xa1
#define PS2_SCAN_CODE_G_PRESSED 0x22
#define PS2_SCAN_CODE_G_RELEASED 0xa2
#define PS2_SCAN_CODE_H_PRESSED 0x23
#define PS2_SCAN_CODE_H_RELEASED 0xa3
#define PS2_SCAN_CODE_I_PRESSED 0x17
#define PS2_SCAN_CODE_I_RELEASED 0x97
#define PS2_SCAN_CODE_J_PRESSED 0x24
#define PS2_SCAN_CODE_J_RELEASED 0xa4
#define PS2_SCAN_CODE_K_PRESSED 0x25
#define PS2_SCAN_CODE_K_RELEASED 0xa5
#define PS2_SCAN_CODE_L_PRESSED 0x26
#define PS2_SCAN_CODE_L_RELEASED 0xa6
#define PS2_SCAN_CODE_M_PRESSED 0x32
#define PS2_SCAN_CODE_M_RELEASED 0xb2
#define PS2_SCAN_CODE_N_PRESSED 0x31
#define PS2_SCAN_CODE_N_RELEASED 0xb1
#define PS2_SCAN_CODE_O_PRESSED 0x18
#define PS2_SCAN_CODE_O_RELEASED 0x98
#define PS2_SCAN_CODE_P_PRESSED 0x19
#define PS2_SCAN_CODE_P_RELEASED 0x99
#define PS2_SCAN_CODE_Q_PRESSED 0x10
#define PS2_SCAN_CODE_Q_RELEASED 0x90
#define PS2_SCAN_CODE_R_PRESSED 0x13
#define PS2_SCAN_CODE_R_RELEASED 0x93
#define PS2_SCAN_CODE_S_PRESSED 0x1f
#define PS2_SCAN_CODE_S_RELEASED 0x9f
#define PS2_SCAN_CODE_T_PRESSED 0x14
#define PS2_SCAN_CODE_T_RELEASED 0x94
#define PS2_SCAN_CODE_U_PRESSED 0x16
#define PS2_SCAN_CODE_U_RELEASED 0x96
#define PS2_SCAN_CODE_V_PRESSED 0x2f
#define PS2_SCAN_CODE_V_RELEASED 0xaf
#define PS2_SCAN_CODE_W_PRESSED 0x11
#define PS2_SCAN_CODE_W_RELEASED 0x91
#define PS2_SCAN_CODE_X_PRESSED 0x2d
#define PS2_SCAN_CODE_X_RELEASED 0xad
#define PS2_SCAN_CODE_Y_PRESSED 0x15
#define PS2_SCAN_CODE_Y_RELEASED 0x95
#define PS2_SCAN_CODE_Z_PRESSED 0x2c
#define PS2_SCAN_CODE_Z_RELEASED 0xac
#define PS2_SCAN_CODE_0_PRESSED 0x0b
#define PS2_SCAN_CODE_0_RELEASED 0x8b
#define PS2_SCAN_CODE_1_PRESSED 0x02
#define PS2_SCAN_CODE_1_RELEASED 0x82
#define PS2_SCAN_CODE_2_PRESSED 0x03
#define PS2_SCAN_CODE_2_RELEASED 0x83
#define PS2_SCAN_CODE_3_PRESSED 0x04
#define PS2_SCAN_CODE_3_RELEASED 0x84
#define PS2_SCAN_CODE_4_PRESSED 0x05
#define PS2_SCAN_CODE_4_RELEASED 0x85
#define PS2_SCAN_CODE_5_PRESSED 0x06
#define PS2_SCAN_CODE_5_RELEASED 0x86
#define PS2_SCAN_CODE_6_PRESSED 0x07
#define PS2_SCAN_CODE_6_RELEASED 0x87
#define PS2_SCAN_CODE_7_PRESSED 0x08
#define PS2_SCAN_CODE_7_RELEASED 0x88
#define PS2_SCAN_CODE_8_PRESSED 0x09
#define PS2_SCAN_CODE_8_RELEASED 0x89
#define PS2_SCAN_CODE_9_PRESSED 0x0a
#define PS2_SCAN_CODE_9_RELEASED 0x8a
#define PS2_SCAN_CODE_ESCAPE_PRESSED 0x01
#define PS2_SCAN_CODE_ESCAPE_RELEASED 0x81
#define PS2_SCAN_CODE_LEFT_SHIFT_PRESSED 0x2a
#define PS2_SCAN_CODE_LEFT_SHIFT_RELEASED 0xaa
#define PS2_SCAN_CODE_RIGHT_SHIFT_PRESSED 0x36
#define PS2_SCAN_CODE_RIGHT_SHIFT_RELEASED 0xb6
#define PS2_SCAN_CODE_BACKSPACE_PRESSED 0x0e
#define PS2_SCAN_CODE_BACKSPACE_RELEASED 0x8e
#define PS2_SCAN_CODE_ENTER_PRESSED 0x1c
#define PS2_SCAN_CODE_ENTER_RELEASED 0x9c
#define PS2_SCAN_CODE_SPACE_PRESSED 0x39
#define PS2_SCAN_CODE_SPACE_RELEASED 0xb9

char ps2_scan_code_chars[256];

void ps2_print();

#endif
