// Generated by scripts/codegen/generate_system_calls.py

const georgios = @import("georgios.zig");

pub inline fn print_string(s: []const u8) void {
    asm volatile ("int $100" ::
        [syscall_number] "{eax}" (@as(u32, 0)),
        [arg1] "{ebx}" (@ptrToInt(&s)),
        );
}

pub inline fn yield() void {
    asm volatile ("int $100" ::
        [syscall_number] "{eax}" (@as(u32, 2)),
        );
}

pub inline fn exit(status: u8) noreturn {
    asm volatile ("int $100" ::
        [syscall_number] "{eax}" (@as(u32, 3)),
        [arg1] "{ebx}" (status),
        );
    unreachable;
}

pub inline fn exec(info: *const georgios.ProcessInfo) bool {
    var failure: bool = undefined;
    asm volatile ("int $100" ::
        [syscall_number] "{eax}" (@as(u32, 4)),
        [arg1] "{ebx}" (info),
        [arg2] "{ecx}" (@ptrToInt(&failure)),
        );
    return failure;
}

pub inline fn get_key() georgios.keyboard.Event {
    var key: georgios.keyboard.Event = undefined;
    asm volatile ("int $100" ::
        [syscall_number] "{eax}" (@as(u32, 5)),
        [arg1] "{ebx}" (@ptrToInt(&key)),
        );
    return key;
}

pub inline fn next_dir_entry(iter: *georgios.DirEntry) bool {
    var rv: bool = undefined;
    asm volatile ("int $100" ::
        [syscall_number] "{eax}" (@as(u32, 6)),
        [arg1] "{ebx}" (iter),
        [arg2] "{ecx}" (@ptrToInt(&rv)),
        );
    return rv;
}

pub inline fn print_hex(value: u32) void {
    asm volatile ("int $100" ::
        [syscall_number] "{eax}" (@as(u32, 7)),
        [arg1] "{ebx}" (value),
        );
}
